module.exports = {
  BOARD_SIZE: 30,
  INITIAL_TICK_MS: 220,
  MIN_TICK_MS: 80,
  SPEED_UP_INTERVAL_MS: 8000,
  SPEED_UP_STEP_MS: 15,
  MAX_PLAYERS: 4,
  MIN_PLAYERS_TO_START: 2,
  POWERUP_SPAWN_CHANCE: 0.02,
  COUNTDOWN_SECONDS: 3,
  OBSTACLE_COUNT: 10,
};
